apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fluttering-grouse-go 
  janus-idp.io/tekton: fluttering-grouse-go
  backstage.io/kubernetes-id: fluttering-grouse-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fluttering-grouse-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  