apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fluttering-grouse-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fluttering-grouse-go 
  name: fluttering-grouse-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fluttering-grouse-go 
